# Generated by Django 4.2.7 on 2025-07-25 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the poll', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the poll')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this poll expires')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the poll is active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Option text', max_length=200)),
                ('vote_count', models.PositiveIntegerField(default=0, help_text='Number of votes for this option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_ip', models.GenericIPAddressField(help_text='IP address of the voter')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll')),
            ],
            options={
                'indexes': [models.Index(fields=['poll', 'voter_ip'], name='polls_vote_poll_id_83027b_idx'), models.Index(fields=['voted_at'], name='polls_vote_voted_a_cca77e_idx')],
                'unique_together': {('poll', 'voter_ip')},
            },
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['poll'], name='polls_pollo_poll_id_9abd98_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['created_at'], name='polls_poll_created_3f3b19_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['expires_at'], name='polls_poll_expires_0c4433_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['is_active'], name='polls_poll_is_acti_53c655_idx'),
        ),
    ]
